name: Release Package

on:
  push:
    tags:
      - 'v*'

jobs:
  release-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Download repository code to runner
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Update manifest version to match tag
      - name: Update manifest version
        run: |
          sed -i 's/"version": "[^"]*"/"version": "'"${GITHUB_REF_NAME#v}"'"/' custom_components/tper_tracker/manifest.json

      # Generate release notes from git history
      - name: Generate release notes
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          echo "**What's Changed:**" > notes.md
          if [ -z "$PREV_TAG" ]; then
            git log --pretty=format:"* %s by @%an" --reverse --no-merges HEAD >> notes.md
          else
            git log --pretty=format:"* %s by @%an" --reverse --no-merges $PREV_TAG..HEAD >> notes.md
          fi
          awk '!seen[$0]++' notes.md > notes_clean.md
          mv notes_clean.md notes.md
          if [ $(wc -l < notes.md) -eq 1 ]; then
            echo "* Initial release by @$(git log --pretty=format:'%an' -1)" >> notes.md
          fi

      # Create integration package
      - name: Create package
        run: |
          cd custom_components/tper_tracker
          zip -r ../../tper_tracker.zip .
          
      # Upload package to release
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          body_path: notes.md
          files: tper_tracker.zip
          draft: false
          prerelease: false